### ISSUE TITLE
2021 React Conf 讨论

### ISSUE THREAD

**Issue by Jokcy** [Jokcy/AMA#2]
[文章链接](https://www.coursebetter.com/normal/2021/about-react-conf)。

这里是Jokcy的AMA，同时也是Jokcy的网站评论保存的地方，你可以在这里进行评论和回复，这些内容会同步到Jokcy的网站，比如这一条issue的讨论就会出现在上面的文章里面。

**Comment by xiaoyu2er** [comment]
请问博客本身有开源么

**Comment by Jokcy** [comment]
@xiaoyu2er 没有的哦，未来有机会可能会考虑
